[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[env]
NIXPACKS_NODE_VERSION = "20"

[deploy]
preDeployCommand = "npm run cleanup-redis"
startCommand = "npm run start"
healthcheckPath = "/api/health"

[deploy.timeout]
read = 3600
write = 3600
